{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "HTTP requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_count_total_requests{source=\"jwt-pizza-service\"}[1m]))\n",
     "legendFormat": "all"
    },
    {
     "expr": "sum by (method) (rate(http_request_count_total_requests{source=\"jwt-pizza-service\", method!~\"HEAD|OPTIONS\"}[1m]))\n\n",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pizza_revenue_total_USD{source=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(auth_attempts_total{source=\"jwt-pizza-service\", status=\"fail\"}[1m]) * 60",
     "legendFormat": "failure"
    },
    {
     "expr": "rate(auth_attempts_total{source=\"jwt-pizza-service\", status=\"success\"}[1m]) * 60",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_usage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "user_active_total_users{source=\"jwt-pizza-service\"}",
     "legendFormat": "active users"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_usage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(http_request_duration_ms_milliseconds{source=\"jwt-pizza-service\"})\n",
     "legendFormat": "Request Latency"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(pizza_purchase_duration_ms_milliseconds{source=\"jwt-pizza-service\"})",
     "legendFormat": "Pizza Latency"
    }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(pizza_purchase_total_purchases{source=\"jwt-pizza-service\", status=\"success\"}[1m]) * 60",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(pizza_purchase_total_purchases{source=\"jwt-pizza-service\", status=\"fail\"}[1m]) * 60 ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}